name: booking_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  barcode: ^2.2.3
  barcode_widget: ^2.0.3
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  division: ^0.9.0
  faker: ^2.0.0
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^7.6.0
  flutter_login: ^4.0.0
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  simple_animations: ^5.0.0+2
  supercharged: ^2.1.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true
